[theme]
# Primary accent for interactive elements
primaryColor = '#4A90E2'

# Background color for the main content area
backgroundColor = '#dce0e4ff'

# Color used for almost all text
textColor = '#2C3E50'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"

[theme.sidebar]
backgroundColor = '#bbc1c8ff'
